### ISSUE TITLE
SRX - "show security monitoring" parser

### ISSUE THREAD

**Issue by mziegler8888** [Juniper/open-nti#170]
Hi All,

anyone working on a "show security monitoring" parser for SRX devices? Would be nice to also see CPU, memory and flows/sessions on a per FPC/PIC basis in the dashboard.

Thanks,

Martin

show security monitoring
node0:
--------------------------------------------------------------------------
                  Flow session   Flow session     CP session     CP session
FPC PIC CPU Mem        current        maximum        current        maximum
  0   0   0  13              0              0              0              0
  0   1   0   6             96        6291456            101        7549747
  0   2   0   6             89        6291456             89        7549747
  0   3   0   6             99        6291456             99        7549747
Total Sessions:            284       18874368            289       22649241

node1:
--------------------------------------------------------------------------
                  Flow session   Flow session     CP session     CP session
FPC PIC CPU Mem        current        maximum        current        maximum
  0   0   0  13              0              0              0              0
  0   1   0   6             77        6291456             79        7549747
  0   2   0   6             70        6291456             70        7549747
  0   3   0   6             72        6291456             75        7549747
Total Sessions:            219       18874368            224       22649241

**Comment by 3fr61n** [comment]
Hi

Could you please put the output command in xml?

Thanks

**Comment by mziegler8888** [comment]
Sure...

`<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <multi-routing-engine-results>

        <multi-routing-engine-item>

            <re-name>node0</re-name>

            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>0</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>13</spu-memory-utilization>
                    <spu-current-flow-session>0</spu-current-flow-session>
                    <spu-max-flow-session>0</spu-max-flow-session>
                    <spu-current-cp-session>0</spu-current-cp-session>
                    <spu-max-cp-session>0</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>1</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>77</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>89</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>2</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>73</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>73</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>3</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>75</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>75</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>Total Sessions:</fpc-number>
                    <pic-number></pic-number>
                    <spu-cpu-utilization></spu-cpu-utilization>
                    <spu-memory-utilization></spu-memory-utilization>
                    <spu-current-flow-session>225</spu-current-flow-session>
                    <spu-max-flow-session>18874368</spu-max-flow-session>
                    <spu-current-cp-session>237</spu-current-cp-session>
                    <spu-max-cp-session>22649241</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
        </multi-routing-engine-item>

        <multi-routing-engine-item>

            <re-name>node1</re-name>

            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>0</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>13</spu-memory-utilization>
                    <spu-current-flow-session>0</spu-current-flow-session>
                    <spu-max-flow-session>0</spu-max-flow-session>
                    <spu-current-cp-session>0</spu-current-cp-session>
                    <spu-max-cp-session>0</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>1</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>46</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>46</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>2</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>34</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>34</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>0</fpc-number>
                    <pic-number>3</pic-number>
                    <spu-cpu-utilization>0</spu-cpu-utilization>
                    <spu-memory-utilization>6</spu-memory-utilization>
                    <spu-current-flow-session>47</spu-current-flow-session>
                    <spu-max-flow-session>6291456</spu-max-flow-session>
                    <spu-current-cp-session>47</spu-current-cp-session>
                    <spu-max-cp-session>7549747</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
            <performance-summary-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-spu-mon">
                <performance-summary-statistics>
                    <fpc-number>Total Sessions:</fpc-number>
                    <pic-number></pic-number>
                    <spu-cpu-utilization></spu-cpu-utilization>
                    <spu-memory-utilization></spu-memory-utilization>
                    <spu-current-flow-session>127</spu-current-flow-session>
                    <spu-max-flow-session>18874368</spu-max-flow-session>
                    <spu-current-cp-session>127</spu-current-cp-session>
                    <spu-max-cp-session>22649241</spu-max-cp-session>
                </performance-summary-statistics>
            </performance-summary-information>
        </multi-routing-engine-item>

    </multi-routing-engine-results>
    <cli>
        <banner>{primary:node0}</banner>
    </cli>
</rpc-reply>
`

**Comment by 3fr61n** [comment]
Question, 

It is possible to have the same command per node?  like 'show security monitoring node0' and 'show security monitoring node1' ?

Regards

**Comment by mziegler8888** [comment]
Yes, it's possible.

**Comment by 3fr61n** [comment]
I don't have any lab to test it....  

Could you please do it for me?  or if I can have access to your setup.

Regards

```
parser:
    regex-command: show\s+security\s+monitoring\s+\|\s+display\s+xml
    matches:
    -
        type: multi-value
        method: xpath
        xpath: //*[local-name() = 'multi-routing-engine-item']/*[local-name() = 'performance-summary-information']/*[local-name() = 'performance-summary-statistics']
        loop:
            node: ../../*[local-name() = 're-name']
            fpc: ./*[local-name() = 'fpc-number']
            pic: ./*[local-name() = 'pic-number']
            sub-matches:
            -
                xpath: ./*[local-name() = 'spu-cpu-utilization']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-cpu-utilization
            -
                xpath: ./*[local-name() = 'spu-memory-utilization']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-memory-utilization
            -
                xpath: ./*[local-name() = 'spu-current-flow-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-current-flow-session
            -
                xpath: ./*[local-name() = 'spu-max-flow-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-max-flow-session
            -
                xpath: ./*[local-name() = 'spu-current-cp-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-current-cp-session
            -
                xpath: ./*[local-name() = 'spu-max-cp-session']
                variable-name:  $host.security.monitoring.node$node.fpc$fpc.pic$pic.spu-max-cp-session

```

**Comment by mziegler8888** [comment]
`[fw-01-nbg04]: Executing command: show security monitoring | display xml
[fw-01-nbg04]: Exception found.
'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/opt/open-nti/open-nti.py", line 400, in parse_result
    keys[key_tmp]=node.xpath(keys_tmp[key_tmp])[0].text.replace(" ","_").strip()
AttributeError: 'NoneType' object has no attribute 'replace'
`

**Comment by 3fr61n** [comment]
I'll try to find a vSRX in cluster to test it :(

**Comment by 3fr61n** [comment]
Sorry by my delay but I'm still looking for a testing environment (security is not my forte :) )

**Comment by mziegler8888** [comment]
Absolutely no problem. Take your time ;)

Unfortunately I cannot give you access to the cluster. The only thing i can offer you is testing and/or providing output.

**Comment by 3fr61n** [comment]
Hi @mziegler8888 

I just committed a new parser using the same logic (more than one 'key' in the multi value block)

https://github.com/Juniper/open-nti/blob/master/data/junos_parsers/show-ddos-protection-protocols-statistics-terse.parser.yaml

and it works, so IMHO there is something else we are missing in the srx scenario.

**Comment by mziegler8888** [comment]
Hi Efrain,

just checked again and found out that it still throws an exception but it looks like metrics are collected properly. Will wait for a few minutes to check if metrics are available.

Thank you,

Martin

root@telemetry:/opt/open-nti# make cron-debug TAG=srx5400
docker exec -i -t opennti_con /usr/bin/python /opt/open-nti/open-nti.py -s -c --tag srx5400
Collector Thread-1 scheduled with following hosts: ['<host>.<tld>']
Connecting to host: <host>.<tld>
[<host>.<tld>]: Executing command: show version | display xml
[<host>.<tld>]: Host will now be referenced as : <host>
[<host>]: Executing command: show security monitoring | display xml
[<host>]: Exception found.
'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/opt/open-nti/open-nti.py", line 400, in parse_result
    keys[key_tmp]=node.xpath(keys_tmp[key_tmp])[0].text.replace(" ","_").strip()
AttributeError: 'NoneType' object has no attribute 'replace'
[<host>]: Parser found and processed, going to next comand.
[<host>]: timestamp_tracking - CLI collection 4
Inserting into database the following datapoints:
[{'fields': {'delta_str': 'N/A', 'value_str': 'srx5400'},
  'measurement': 'base-info',
  'tags': {'device': '<host>',
           'kpi': 'base-info',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-cpu-utilization',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 13},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-memory-utilization',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-current-flow-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-max-flow-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-current-cp-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 0},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic0.spu-max-cp-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 32, 'value': 32},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-cpu-utilization',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-memory-utilization',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 22197, 'value': 22280},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-current-flow-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-max-flow-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 22363, 'value': 22446},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-current-cp-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic1.spu-max-cp-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 32, 'value': 32},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-cpu-utilization',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-memory-utilization',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21410, 'value': 21486},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-current-flow-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-max-flow-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 22959, 'value': 23035},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-current-cp-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic2.spu-max-cp-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 29, 'value': 29},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-cpu-utilization',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-memory-utilization',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21804, 'value': 21879},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-current-flow-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-max-flow-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 22010, 'value': 22085},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-current-cp-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 0, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '0',
           'kpi': '<host>.security.monitoring.nodenode0.fpc0.pic3.spu-max-cp-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 33, 'value': 33},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-cpu-utilization',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-memory-utilization',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21716, 'value': 21716},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-current-flow-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6291456, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-max-flow-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21926, 'value': 21926},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-current-cp-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 7549747, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic0.spu-max-cp-session',
           'node': 'node0',
           'pic': '0',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 30, 'value': 30},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-cpu-utilization',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-memory-utilization',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21853, 'value': 21853},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-current-flow-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6291456, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-max-flow-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 22077, 'value': 22077},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-current-cp-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 7549747, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic1.spu-max-cp-session',
           'node': 'node0',
           'pic': '1',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 29, 'value': 29},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-cpu-utilization',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-memory-utilization',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21147, 'value': 21147},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-current-flow-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6291456, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-max-flow-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21352, 'value': 21352},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-current-cp-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 7549747, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic2.spu-max-cp-session',
           'node': 'node0',
           'pic': '2',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 25, 'value': 25},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-cpu-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-cpu-utilization',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6, 'value': 6},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-memory-utilization',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-memory-utilization',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21707, 'value': 21707},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-current-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-current-flow-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 6291456, 'value': 6291456},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-max-flow-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-max-flow-session',


           'node': 'node0',
           'pic': '3',


           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 21885, 'value': 21885},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-current-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-current-cp-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 7549747, 'value': 7549747},
  'measurement': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-max-cp-session',
  'tags': {'device': '<host>',
           'fpc': '1',
           'kpi': '<host>.security.monitoring.nodenode0.fpc1.pic3.spu-max-cp-session',
           'node': 'node0',
           'pic': '3',
           'product-model': 'srx5400',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 5, 'value': 5},
  'measurement': 'open-nti-stats',
  'tags': {'device': '<host>',
           'kpi': 'open-nti-stats',
           'product-model': 'srx5400',
           'stats': 'collection-time',
           'version': '15.1X49-D90.7'}},
 {'fields': {'delta': 1, 'value': 1},
  'measurement': 'open-nti-stats',
  'tags': {'device': '<host>',
           'kpi': 'open-nti-stats',
           'product-model': 'srx5400',
           'stats': 'collection-successful',
           'version': '15.1X49-D90.7'}}]
[<host>]: timestamp_tracking - total collection 5

**Comment by mziegler8888** [comment]
Just recognized that metrics are only for node 0 but not for node 1. Perhaps that has something to do with the exception…
